### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by AntoniosBarotsis** [sysid/bkmr#1]
I'm not sure if the crate has not been published yet but I can't seem to find it in crates.io, not sure what you mean by "standard Rust install via `cargo`" :)

Edit: I'm not sure if by that you meant running `cargo install` in the repo after cloning it but if that's the case, I could help setting up a CD pipeline if you're interested. I've done this a few times for my own projects.

**Comment by sysid** [comment]
@AntoniosBarotsis Toni you are right, I did not find the time yet for proper installation process, but will attend to it as soon as I find the time. For now it's basically `cargo build --release` and then put the resulting binary somewhere in your path. If you have a workflow for publishing I am definitely interested. Thanks for your feedback!

**Comment by AntoniosBarotsis** [comment]
You can take a look at [this](https://github.com/AntoniosBarotsis/qr-rs/blob/master/.github/workflows/release-lib.yml).

You need to add a Github sercet `CRATESIO_TOKEN ` and set it to a crates.io token.

**Comment by sysid** [comment]
@AntoniosBarotsis, thank you for your trigger and example! Published the crate.

**Comment by sysid** [comment]
Hi @AntoniosBarotsis , if you like bkmr you can give it a vote on[ "crate of the week"](https://users.rust-lang.org/t/crate-of-the-week/2704/1158).
