### ISSUE TITLE
Outputting as plain text

### ISSUE THREAD

**Issue by theodopolopodous** [sysid/bkmr#13]
Hi, thanks for the cool tool

Is there a way to output all bookmarks as plain text?  Maybe grouped by tags?

**Comment by sysid** [comment]
`bkmr search --np 1>/dev/null`, but this is neither elegant nor true plain text. It still has the color coding in it.

You just want to have plain text without the ANSI color codes I guess?

**Comment by sysid** [comment]
Created a new version with two features:
1) detect TTY, so when used with `bkmr search --np 1>/dev/null` no more ANSI color codes will be output
2) `bkmr search --json` will output of json dump of your search results.

Hope this helps.

**Comment by theodopolopodous** [comment]
Thank you so much :)  Very handy!

**Comment by HelionSmoker** [comment]
If anyone is using a pager, such as `less` to view the output, running `bkmr search --np 1>/dev/null` will only catch the found ids. To see the rest, use `bkmr search --np 1>/dev/null 2>&1 | less`. With the newest change, there's no color, but 🤷... Maybe a `--color=always` à la `ls` and `grep` would work?
