### ISSUE TITLE
Filter out tags from results?

### ISSUE THREAD

**Issue by tjex** [sysid/bkmr#14]
Hello. 
Thanks for the great utility, and the rewrite in Rust! Super snappy. 

I'm wondering, is there a way to filter out tags from search results?
I thought that's what the `-n` flag in the readme was going to be doing, but apparently not.

I'm thinking a long the lines of:
`bkmr search -t tech -n education`

Which would return all bookmarks that have tags `tech` and *not* `education`

**Comment by sysid** [comment]
I think what you are looking for it `-N`.

**Comment by tjex** [comment]
yup! Thanks
