### ISSUE TITLE
Bookmarks tags output (fzf)

### ISSUE THREAD

**Issue by egovelox** [sysid/bkmr#18]
Hi @sysid !

Great to see so much nice work going on !

I found a small and unpleasant bug, coming from my previous PR (months ago !) 

### To reproduce : 

```bash
export BKMR_FZF_OPTS="--reverse --show-tags""

bkmr add notes1.md notes --title "A dummy note"

bkmr search --limit 100 --fzf
```
<img width="433" alt="Screenshot 2024-01-23 at 1 45 13 AM" src="https://github.com/sysid/bkmr/assets/56078155/6619aa1d-769b-4294-a9cc-a4cd04ff7e5b">

In the search output, we can see that the tag ``notes`` is surrounded by ``  |  `` before and after, as if it was surrounded by two empty tags.

### To fix :
When running ``bkmr add``, I did not notice that the ``create_normalized_tag_string()`` function would add two commas, one before and one after the tags - this is the way you chose to store tags in the database.

Then, when ``--show-tags`` comes into play during ``search --fzf`` it should take that peculiarity into account, when replacing commas with the ``|`` delimiter.

### Expected behaviour

<img width="1242" alt="Screenshot 2024-01-23 at 3 02 09 AM" src="https://github.com/sysid/bkmr/assets/56078155/8dd0d53e-5286-48af-9a0d-705670374add">

I can emit a PR to fix that bug, I'll do it very soon 🙏 

Note : in fact I was not using ``bkmr add`` until recently (I rather inserted my browser bookmarks periodically directly into sqlite), and that's why I did not find that bug sooner.

Cheers,

**Comment by sysid** [comment]
@egovelox , thanks for your proposal I am happy to take it. Would not call it a bug, though. But definitely improves UX.
