### ISSUE TITLE
Error in the `README` about the benchmark

### ISSUE THREAD

**Issue by woshilapin** [sysid/bkmr#2]
I believe there is an error about the `README` information on benchmarking.

The comparison is incorrect since the measurement for `bkmr` is not really there (see error message).

```
time bmkr search 'zzz*' --np
-bash: bmkr: command not found
```

**Comment by sysid** [comment]
@woshilapin , thanks for spotting this error! I fixed it. Although the overall numbers are both higher due to growth in URL database, the general statement holds, though.

**Comment by sysid** [comment]
Hi @woshilapin , if you like bkmr you can give it a vote on[ "crate of the week"](https://users.rust-lang.org/t/crate-of-the-week/2704/1158).
