### ISSUE TITLE
Failed to insert new bookmark

### ISSUE THREAD

**Issue by egovelox** [sysid/bkmr#6]
Hi !

I wish I could give a try to `bkmr` !
I set up everything, all seems ok at first, but I got an error when inserting my first bookmark 🙏 

Probably due to `sqlite` RETURNING clause ?
https://sqlite.org/forum/info/a4dde39b614ec0b2

I tried to update my sqlite3 version, but that dit not fix it.
I'm running `MacOS 11.6.1` (Big Sur)

Help would be appreciated !
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/56078155/219941055-da611eef-5291-4d27-8649-3b4894b22e7e.png">

**Comment by egovelox** [comment]
I could fix it on my own :

I cloned bkmr and added a line in `bkmr/Cargo.toml` :

`rusqlite = { version = "0.28.0", features = ["bundled"] }`

And now I can make it work with :
`cargo run -- add 'https://surma.dev/things/rust-to-webassembly' rust,wasm --description "An article about rust and wasm"`

Seems to me that, currently, it's the only way on my system to link `diesel` with a recent `sqlite3` version (allowing RETURNING).

I wonder if you would agree to add `rusqlite` to `bkmr` dependencies as well, 
so that I could use it without having to clone & adapt it ! 🙏 

I might also upgrade macOS and see, but you know... 😮‍💨 

Any other solutions are welcome !

**Comment by sysid** [comment]
@egovelox Added in new release. Any idea why this is the case?

**Comment by egovelox** [comment]
Not sure, I guess that, 
because `sqlite` is shipped with macOS, 
`diesel` always uses the macOS default, 
making impossible to bind it with another custom (e.g `brew`) `sqlite`.

Well, `rusqlite` is made for that, 
if I read [the docs](https://github.com/rusqlite/rusqlite)
> and avoids depending on the version of SQLite on the users system (or your system), which may be old or missing

Thanks for the next release, 
I'm trying `bkmr` now,  and I'm beginning to ❤️ it !
