### ISSUE TITLE
Pull-request-request ?

### ISSUE THREAD

**Issue by egovelox** [sysid/bkmr#9]
Hi !

Are you open to any contribution (pull-requests) for this great project ?

I actually use `bkmr` with 2 personal features I recently added to your code running on my local machine :

- BKMR_FZF_OPTS env-variable allowing to change `skim` options (only `--reverse`, `--height` for now)
- an option to print tags during `bkmr --fzf` mode (I mean a simple flag `--show-tags` in the same env-variable)

Would you agree to have these features in a new pull-request ?
How could I push to your project ?
(I currently have a 403 trying to push my branch)

**Comment by sysid** [comment]
@egovelox , yes I am open for features which might be useful to everybody. To make a pull request the minimum requirement would be to make `make test` run without issues and the README.md is updated. Looking forward to your ideas.

**Comment by egovelox** [comment]
Alright then !
Could you please help, it seems I cannot push my branch properly 🙏 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/56078155/221403480-4a96b0dd-24d8-4348-8645-5b25b2dee021.png">

**Comment by egovelox** [comment]
Fixed it : I just had to fork your repo first.
